steps:
- name: gcr.io/cloud-builders/gcloud
  args:
    - kms
    - decrypt
    - --ciphertext-file=secrets.json.enc
    - --plaintext-file=secrets.json
    - --location=global
    - --keyring=k8s
    - --key=gcs
- name: gcr.io/cloud-builders/bazel
  args: ['version']
- name: gcr.io/cloud-builders/bazel
  args: [
    'test',
    '--remote_http_cache=https://storage.googleapis.com/bazel-cache-cs',
    '--experimental_remote_spawn_cache',
    '--google_credentials=secrets.json',
    '//pkg/...'
  ]
# timeout: 3600s
# options: {
#   machineType: N1_HIGHCPU_32
# }
